### PR TITLE
Walkthrough

### PR DESCRIPTION
**Pull request by StefanScherer**
Here is my walkthrough which currently runs at https://lerndieuhr.packerbuilder.xyz, and https://portainer.packerbuilder.xyz ... :-)

Wow, docker configs makes very easy to keep the config file local in git.
I don't know how to update the config, another redeploy shows an error.
But I just used `docker stack rm test` and another `docker stack deploy -c docker-compose.yml test` to recreate everything.

### CODE REVIEW

**Comment by StefanScherer** [comment]
Ok, configs are immutable https://github.com/moby/moby/issues/35048

**Comment by StefanScherer** [comment]
And a blog post about such a deployment would be fine https://twitter.com/stefscherer/status/981787520617852928 :-)

**Comment by nathanaherne** [comment]
I tried to read your walkthrough but it seems that you have a problem with your Traefik configuration - it is serving the default (self signed) cert (and I get a Firefox error) instead of one (I assume) from LetsEncrypt.

**Comment by StefanScherer** [comment]
@nathanaherne Well it worked on my Azure box (with a different FQDN that I have registered and configured the the IP of the Azure box).
You can check the logs of the traefik service with eg. `docker service logs test_traefik` (or the different stack name before the underscore). Probably Traefik had some difficulties to get the correct certs and then uses its default certs.

For testing things a good recommendation is to use the staging certs from Let's Encrypt if you enable the line with `caServer`. Of course you then get also untrusted certs, but from Let's Encrypt.

**Comment by nathanaherne** [comment]
@StefanScherer I didn't explain myself correctly. When I went to the links above to read your walk through, I got an SSL error from Firefox on my Mac and I could see your Traefik configuration was serving the default self signed certs (to me), not ones from Lets Encrypt.

**Comment by StefanScherer** [comment]
@nathanaherne You have to adjust the traefik.toml and docker-compose.yml with your own domain name. And you have to enter the IP address in your DNS provider, also the sub domains.
Please have a look at the errors in traefik output.
This PR isn't a full blog post what to do. After some cleanup I hope to write a blog post that explains more.

**Comment by nathanaherne** [comment]
This is the first post I see in this pull request. This is what I am commenting on.

screen shot 2018-04-11 at 8 43 59 am

**Pull request merged**
